// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BulkPreview(arg1, arg2, arg3) {
  return window['go']['app']['App']['BulkPreview'](arg1, arg2, arg3);
}

export function BulkRun(arg1) {
  return window['go']['app']['App']['BulkRun'](arg1);
}

export function CloseConsole(arg1) {
  return window['go']['app']['App']['CloseConsole'](arg1);
}

export function CompressValue(arg1, arg2) {
  return window['go']['app']['App']['CompressValue'](arg1, arg2);
}

export function ConsoleExecute(arg1, arg2) {
  return window['go']['app']['App']['ConsoleExecute'](arg1, arg2);
}

export function ConsoleStartMonitor(arg1) {
  return window['go']['app']['App']['ConsoleStartMonitor'](arg1);
}

export function CreateKey(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['CreateKey'](arg1, arg2, arg3, arg4, arg5);
}

export function DecodeValue(arg1, arg2) {
  return window['go']['app']['App']['DecodeValue'](arg1, arg2);
}

export function DecompressValue(arg1, arg2) {
  return window['go']['app']['App']['DecompressValue'](arg1, arg2);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function DeleteKey(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteKey'](arg1, arg2, arg3);
}

export function DetectCompression(arg1) {
  return window['go']['app']['App']['DetectCompression'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['app']['App']['Disconnect'](arg1);
}

export function EditRow(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['EditRow'](arg1, arg2, arg3, arg4);
}

export function EncodeValue(arg1, arg2) {
  return window['go']['app']['App']['EncodeValue'](arg1, arg2);
}

export function EnsureConnection(arg1) {
  return window['go']['app']['App']['EnsureConnection'](arg1);
}

export function GetClientList(arg1, arg2) {
  return window['go']['app']['App']['GetClientList'](arg1, arg2);
}

export function GetFilterHistory(arg1, arg2) {
  return window['go']['app']['App']['GetFilterHistory'](arg1, arg2);
}

export function GetFullValue(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFullValue'](arg1, arg2, arg3);
}

export function GetServerInfo(arg1, arg2) {
  return window['go']['app']['App']['GetServerInfo'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetSlowLog(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetSlowLog'](arg1, arg2, arg3);
}

export function ImportFromRDM(arg1) {
  return window['go']['app']['App']['ImportFromRDM'](arg1);
}

export function IsBinaryValue(arg1) {
  return window['go']['app']['App']['IsBinaryValue'](arg1);
}

export function ListCompressionAlgs() {
  return window['go']['app']['App']['ListCompressionAlgs']();
}

export function ListConnections() {
  return window['go']['app']['App']['ListConnections']();
}

export function ListFormatters() {
  return window['go']['app']['App']['ListFormatters']();
}

export function LoadKeyRows(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['LoadKeyRows'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function OpenConnection(arg1) {
  return window['go']['app']['App']['OpenConnection'](arg1);
}

export function OpenConsole(arg1, arg2) {
  return window['go']['app']['App']['OpenConsole'](arg1, arg2);
}

export function OpenKey(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['OpenKey'](arg1, arg2, arg3, arg4);
}

export function ProbeExtServer(arg1) {
  return window['go']['app']['App']['ProbeExtServer'](arg1);
}

export function PubSubSubscribe(arg1, arg2) {
  return window['go']['app']['App']['PubSubSubscribe'](arg1, arg2);
}

export function PubSubUnsubscribe(arg1) {
  return window['go']['app']['App']['PubSubUnsubscribe'](arg1);
}

export function RefreshKeys(arg1, arg2, arg3) {
  return window['go']['app']['App']['RefreshKeys'](arg1, arg2, arg3);
}

export function RenameKey(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RenameKey'](arg1, arg2, arg3, arg4);
}

export function SaveConnection(arg1) {
  return window['go']['app']['App']['SaveConnection'](arg1);
}

export function SaveFilterHistory(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveFilterHistory'](arg1, arg2, arg3);
}

export function SaveStringValue(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveStringValue'](arg1, arg2, arg3, arg4);
}

export function SetKeyTTL(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SetKeyTTL'](arg1, arg2, arg3, arg4);
}

export function SetSettings(arg1) {
  return window['go']['app']['App']['SetSettings'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}
