// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {formatter} from '../models';
import {keymodel} from '../models';
import {redisclient} from '../models';
import {serverstats} from '../models';
import {settings} from '../models';

export function BulkPreview(arg1:string,arg2:number,arg3:string):Promise<app.BulkPreview>;

export function BulkRun(arg1:app.BulkRequest):Promise<string>;

export function CloseConsole(arg1:string):Promise<void>;

export function CompressValue(arg1:string,arg2:string):Promise<string>;

export function ConsoleExecute(arg1:string,arg2:string):Promise<string>;

export function ConsoleStartMonitor(arg1:string):Promise<void>;

export function CreateKey(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number):Promise<void>;

export function DecodeValue(arg1:string,arg2:string):Promise<formatter.Result>;

export function DecompressValue(arg1:string,arg2:string):Promise<string>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteKey(arg1:string,arg2:number,arg3:string):Promise<void>;

export function DetectCompression(arg1:string):Promise<string>;

export function Disconnect(arg1:string):Promise<void>;

export function EditRow(arg1:string,arg2:number,arg3:string,arg4:keymodel.EditRequest):Promise<void>;

export function EncodeValue(arg1:string,arg2:string):Promise<string>;

export function EnsureConnection(arg1:redisclient.Config):Promise<app.ConnSummary>;

export function GetClientList(arg1:string,arg2:number):Promise<Array<serverstats.ClientRow>>;

export function GetFilterHistory(arg1:string,arg2:number):Promise<Array<string>>;

export function GetFullValue(arg1:string,arg2:number,arg3:string):Promise<string>;

export function GetServerInfo(arg1:string,arg2:number):Promise<serverstats.InfoSnapshot>;

export function GetSettings():Promise<settings.Settings>;

export function GetSlowLog(arg1:string,arg2:number,arg3:number):Promise<Array<serverstats.SlowLogEntry>>;

export function ImportFromRDM(arg1:string):Promise<number>;

export function IsBinaryValue(arg1:string):Promise<boolean>;

export function ListCompressionAlgs():Promise<Array<string>>;

export function ListConnections():Promise<Array<redisclient.Config>>;

export function ListFormatters():Promise<Array<app.FormatterInfo>>;

export function LoadKeyRows(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number):Promise<keymodel.RowsPage>;

export function OpenConnection(arg1:redisclient.Config):Promise<app.ConnSummary>;

export function OpenConsole(arg1:string,arg2:number):Promise<string>;

export function OpenKey(arg1:string,arg2:number,arg3:string,arg4:string):Promise<keymodel.KeyMeta>;

export function ProbeExtServer(arg1:string):Promise<Array<formatter.ExtFormatterInfo>>;

export function PubSubSubscribe(arg1:string,arg2:string):Promise<string>;

export function PubSubUnsubscribe(arg1:string):Promise<void>;

export function RefreshKeys(arg1:string,arg2:number,arg3:string):Promise<app.TreeResult>;

export function RenameKey(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function SaveConnection(arg1:redisclient.Config):Promise<void>;

export function SaveFilterHistory(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SaveStringValue(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function SetKeyTTL(arg1:string,arg2:number,arg3:string,arg4:number):Promise<void>;

export function SetSettings(arg1:settings.Settings):Promise<void>;

export function TestConnection(arg1:redisclient.Config):Promise<app.TestResult>;
